permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-redirect-from

recommended_posts:
  - url: /blog/2014/03/02/defining-atom-commands-in-your-init-script/
  - url: /blog/2013/01/23/as-creative-as-we-make-time-to-be/
  - url: /blog/2011/08/09/programming-achievements-how-to-level-up-as-a-developer/
  - url: /blog/2009/05/27/git-up-10-reasons-to-upgrade-your-old-git-installation/
  - url: /blog/2008/06/17/testing-anti-patterns-incidental-coverage/
  - url: /blog/2012/09/11/clojurescript-4-things-that-might-worry-you-but-should-not/
